### ISSUE TITLE
Add Synk health Badge

### ISSUE THREAD

**Issue by hasezoey** [typegoose/mongodb-memory-server#561]
Tracking issue to add Synk Badges to the packages

example:
[![mongodb-memory-server-core](https://snyk.io/advisor/npm-package/mongodb-memory-server-core/badge.svg)](https://snyk.io/advisor/npm-package/mongodb-memory-server-core)

@nodkz should we add this to all packages?

**Comment by nodkz** [comment]
I didn't use it before. But synk provides quite good analytics and i'll be glad to see it.
