### ISSUE TITLE
Update `mongodb` to `6.0.0`

### ISSUE THREAD

**Issue by hasezoey** [typegoose/mongodb-memory-server#804]
Tracker issue for upgrading dependency `mongodb` from `5.x.x` to `6.0.0`

**Comment by openam** [comment]
Is there any timeline for for the 10.0 milestone? It doesn't look like any of the items in there have been addressed.

**Comment by hasezoey** [comment]
> Is there any timeline for for the 10.0 milestone?

there is no exact timeline, as this is basically a personal project

> It doesn't look like any of the items in there have been addressed.

Version 10.0 is not yet in development as until recently there were some things i wanted to wait on (not strictly blockers), for example getting [MMS 9.x into mongoose](https://github.com/Automattic/mongoose/pull/13764), which i basically use as a extended wider test-case.
Aside from that, it is not really critical to upgrade to mongodb 6.x as the version used in MMS does not (or at least shouldnt) conflict with the application's version, though i understand the de-duplication aspect.
