### ISSUE TITLE
9.1.8 not working out of the box for node:20 docker (LTS images)

### ISSUE THREAD

**Issue by darkalor** [typegoose/mongodb-memory-server#861]
## Versions

- NodeJS: 20
- mongodb-memory-server-*: 9.1.8 
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 0.0.0 
- mongoose: 7.6.10 
- system: Debian 12

package: mongo-memory-server 

## What is the Problem?

On current node LTS (20) docker image (https://hub.docker.com/_/node), which is Debian 12 based 9.1.8 is no longer starting up correctly.

9.1.7 worked fine, although it needed the old libcrypto.

9.1.8 fails with
```
     Error: Requested Version "6.0.9" is not available for "Debian 12"! Available Versions: ">=7.0.3"
Mongodb does not provide binaries for versions before 7.0.3 for Debian 12+ and also cannot be mapped to a previous Debian release
```

I.e. with the default config it tries to use an invalid mongo version (which isn't *that* invalid since it worked in 8.1.7).

## Code Example

```ts
  mongod = await MongoMemoryServer.create();
```

Note: no custom config or anything else set for versions

## Debug Output

N/A

## Do you know *why* it happenes?
🤷

**Comment by hasezoey** [comment]
version [`9.1.8`](https://github.com/nodkz/mongodb-memory-server/releases/tag/v9.1.8) added support for debian 12 without having to use workarounds, which results in this error as there are no "native" binaries for debian 12 for the requested version.

possible fixes (from most to least recommended):
- upgrade to a newer mongodb version (via [`VERSION`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version))
- overwrite the [`DISTRO`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#distro) to be seen as Debian 11 (`debian-11`)
- stick with the older mongodb-memory-server version
- overwrite the [`ARCHIVE_NAME`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#archive_name) or the complete [`DOWNLOAD_URL`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#download_url)
- use a [`SYSTEM_BINARY`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#system_binary) (you will be responsible for downloading and unpacking the binary)

PS: this change was seen as a "patch" as the previous way would require the user to use a workaround (installing a 3rd party package not in the distros repo)

**Comment by hasezoey** [comment]
we currently dont to distro-specific versions, otherwise see [When a (mongodb) Version gets upgraded](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#when-a-version-gets-upgraded)
