### ISSUE TITLE
CommonJS support should be added back

### ISSUE THREAD

**Issue by kevin-boutin** [typegoose/mongodb-memory-server#892]
## Versions

- NodeJS: 20.x
- mongodb-memory-server-*: 10.0.1
- mongodb(the binary version): 0.0.0 
- system: MacOS

package: mongo-memory-server

## What is the Problem?

CommonJS support was removed as of version 10.0.0. Let's shim it so CommonJS is still compatible.

## Debug Output

Error [ERR_REQUIRE_ESM]: require() of ES Module

**Comment by hasezoey** [comment]
to my knowledge this entire project is still CommonJS as ESModules still dont work in jest without extra flags (as of 10.1.0)
