### ISSUE TITLE
Download failed for RHEL 8.0 URLs

### ISSUE THREAD

**Issue by tomhudak** [typegoose/mongodb-memory-server#896]
## Versions

- NodeJS: 20.18.0
- mongodb-memory-server-*: 10.1.2
- mongodb(the binary version): 8.0.1
- system: Linux, Fedora 40

package: mongo-memory-server

## What is the Problem?

Download of the server version failed.
I tried to change the version to 8.0.0 and 7.0.14 and I get the same error (this is what I think was fixed in https://github.com/typegoose/mongodb-memory-server/releases/tag/v10.1.2). 

First it worked with 7.0.14, but then I have deleted my node_modules folder to make sure cache does not interact with it and then it consistently failed.

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
Error: Download failed for url "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel80-8.0.1.tgz", Details:
Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive
    at RedirectableRequest.<anonymous> (/home/tomi/git/urbantz/server/node_modules/@shelf/jest-mongodb/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:272:32)
    at RedirectableRequest.emit (node:events:519:28)
    at RedirectableRequest._processResponse (/home/tomi/git/urbantz/server/node_modules/follow-redirects/index.js:409:10)
    at RedirectableRequest._onNativeResponse (/home/tomi/git/urbantz/server/node_modules/follow-redirects/index.js:102:12)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:702:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
    at TLSSocket.socketOnData (node:_http_client:544:22)
    at TLSSocket.emit (node:events:519:28)
```

</details>

## Do you know *why* it happens?

While resolving the fedora version, it is trying to download from `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel80-8.0.1.tgz` (with 80) while the correct url is `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel8-8.0.1.tgz` (with 8 only).

## Workaround
Before running my code, I set
```
export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel8-8.0.1.tgz
```

**Comment by hasezoey** [comment]
I dont quite understand what you want to say with this issue. Are you meaning to say that you still have a URL issue with `80` being used despite using 10.1.2 on fedora 40?

**Comment by tomhudak** [comment]
Thanks for getting back to me quickly.

_Are you meaning to say that you still have a URL issue with 80 being used despite using 10.1.2 on fedora 40?_
Exactly, that's my problem, and I'm happy for any advice to reset my environment or to point me to a direction I haven't tried yet.

You can find the debug logs [here](https://gist.github.com/tomhudak/0733cbb50c098413002aa7b2a52c9905) and the Distribution Information [here](https://gist.github.com/tomhudak/870fb126e1cf02e582099b5da1004932).

Thank you!

**Comment by hasezoey** [comment]
> You can find the debug logs [here](https://gist.github.com/tomhudak/0733cbb50c098413002aa7b2a52c9905)
> [`  MongoMS:GetPort EXP_NET0LISTEN false +0ms`](https://gist.github.com/tomhudak/0733cbb50c098413002aa7b2a52c9905#file-gistfile1-txt-L49)

guessing by that line, you are running a mongodb-memory-server version before 10.0.0, see 887f1a1e932a8993ef3fd69cf1f65b700c89a77b.

verify you package.json that you are specifying the correct version, then double-check your lockfile

**Comment by tomhudak** [comment]
In my project I'm using https://www.npmjs.com/package/@shelf/jest-mongodb that still depend on mongodb-memory-server 9.2.0, I think that will be the source of my issue. 

Thanks for the help, I continue my journey with them.

**Comment by hasezoey** [comment]
FYI: i backported all the changes related to this (among some others) to 9.x as [`9.5.0`](https://github.com/typegoose/mongodb-memory-server/releases/tag/v9.5.0).

though note that if you are still using `@shelf/jest-mongodb`, you will still have to [overwrite the version](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) as they [strictly require `9.2.0`](https://github.com/shelfio/jest-mongodb/blob/006bfbb853685cddc0cf96846fafb55f4ac2a3ff/package.json#L51)
